//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace News_Search_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinksTable
    {
        public string LinkAdress { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<int> HasIndexed { get; set; }
        public Nullable<System.DateTime> LastIndexedDay { get; set; }
    }
}
